proxy:
  image: proxy
  ports: 
    - 80:80
    - 3000:3000
  links:
    - angular-car-manager
    - node-car-manager
angular-car-manager:
  image: angular-car-manager
  ports:
    - 8080:3001
node-car-manager:
  image: node-car-manager
