#Usuarios
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
	"username": "cjuniorfox",
	"password" : "senha123"
}
###
POST http://localhost:3000/api/user
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODAxNTMzODcsImV4cCI6MTU4MDE1NDU4N30._Be-aC9qzxl7pkbL2dVzLobBe96_tx8qiIC9OPP5-nc

{
	"username": "danieleamorim10",
	"password": "senha123",
	"name": "Daniele Rosa",
	"tel": "21986109042",
	"admin": "true"
}
### 
GET http://localhost:3000/api/user/logout
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEFuc2VsbW8gTWVuZGVzIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTIzMDYzZDc5YzFmODdkMjg2OGUxYjUiLCJpYXQiOjE1Nzk2NDM0MTUsImV4cCI6MTU3OTY0NDAxNX0.C8DK1-EP8TbBEM6Y1ApG_i85n9Yz-qkEjkI0NDf7IOM
###
POST http://localhost:3000/api/user/refresh-token
Content-Type: application/json

{"refreshtoken":"I41XVjwQ5OOCyohBl12XzLv09CUOmEwRKl6Eqz9HkNIZjUE0jeaTqCbF8pqVt3b18X1KpdTquTfXxz1fEanB5z43pIKEjGibND5CVgNY2eCJjJLSYmqVNV0JutB17jFOoIrD1o2uniAKE3eamwbGb2EbD24bgrUfjS6quK5wrCLlqGkjQ6ig3q9ICFGiNQPoOJRLmvZLfOL9bGG3hciOn3p1ViPar0EkrCoTjUiAHLsGNLkPxeIg9f8QoeNkX5xA"}

###
GET http://localhost:3000/api/cliente/buscar
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODEwOTQ2NzcsImV4cCI6MTU4MTA5NTg3N30.8U3iKlaVNjNGO99lE-CBVHPwgbLTWKt4GeJt0sdqi-0

###Fichas
GET http://localhost:3000/api/ficha/listar?ativas=0
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODEwOTQ2NzcsImV4cCI6MTU4MTA5NTg3N30.8U3iKlaVNjNGO99lE-CBVHPwgbLTWKt4GeJt0sdqi-0

###
GET http://localhost:3000/api/ficha/5e307d134125206ca549c89a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODEwODA4NjUsImV4cCI6MTU4MTA4MjA2NX0.5-fsvVawJQW42jtsWUlQr8-eeEZG9MNqXr1SH8BC1Xw

### Deletar serviço
DELETE http://localhost:3000/api/ficha/5e3822ee48d8fe1a866e7d4c/5e3d649cfa75f0d3ca755719
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODExMDEzOTksImV4cCI6MTU4MTEwMjU5OX0.nJMl28eP5pS5uzoQG0KDq5-RbMoMOwxctQTm4-i4jfQ


###
POST http://localhost:3000/api/ficha/5e3021d55cd8591b807ab698/add-servico
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODAyMjE2NzEsImV4cCI6MTU4MDIyMjg3MX0.guyFnMq5kug79D-StU1Sl_v5rWiXV3vlGE4PGmhyFXs

{
    "servico": "Lavagem simples",
    "setor": "OF",
    "box": "Detalhamento",
    "descricao": "Detalhamento da lavagem",
    "inicio": "2019-01-28T10:30"
}
### Finalizar
POST http://localhost:3000/api/ficha/5e3c6eefd9496f2750ea5198/finalizar
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODEwODA4NjUsImV4cCI6MTU4MTA4MjA2NX0.5-fsvVawJQW42jtsWUlQr8-eeEZG9MNqXr1SH8BC1Xw

{
    "at":"2020-02-07T09:45"
}
###

POST http://localhost:3000/api/ficha/update-veiculo/5e3021d55cd8591b807ab698
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNqdW5pb3Jmb3giLCJuYW1lIjoiQ2FybG9zIEp1bmlvciIsImFkbWluIjp0cnVlLCJfaWQiOiI1ZTJmMzYyZmFiZTJjZDFkNjUxZWE2OTgiLCJpYXQiOjE1ODAyMjAwNzEsImV4cCI6MTU4MDIyMTI3MX0.A0TRYSGxbLdUTMMHZzMHnpvaDpfLasZ2s9c3aHNfTd4

{
    "servico": "Lavagem simples",
    "setor": "OF",
    "box": "Detalhamento",
    "descricao": "Detalhamento da lavagem",
    "inicio": "2019-01-28T10:30"
}